name: judo_icon_helper
description: This provides access to the full library of Icons & FontAwesomeIcons & Mdi at runtime when the specific icons needed are not known at compile time.
version: 1.0.0
homepage: https://github.com/BlackBeltTechnology/judo-icon-helper

dependencies:
  flutter:
    sdk: 'flutter'
  material_design_icons_flutter: ^5.0.6295

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any

environment:
  sdk: ">=2.14.0 <3.0.0"

flutter:
  uses-material-design: true
